# Private : Public : shortcut : dns : user_name : password : master_key : tools 
10.2.1.216:172.16.5.108:master1:master1.cloudwick.com:root:pass:master1_key_rsa:ambari-client
10.2.1.194:172.16.5.109:master2:master2.cloudwick.com:root:pass:master2_key_rsa:ambari-client
10.2.1.230:172.16.5.110:ambari:ambari.cloudwick.com:root:pass:ambari_key_rsa:ambari-server,mysql
10.2.1.229:172.16.5.111:data1:data1.cloudwick.com:root:pass:data1_key_rsa:ambari-client
10.2.1.218:172.16.5.112:data2:data2.cloudwick.com:root:pass:data2_key_rsa:ambari-client
